/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tic.tac.toe;

public class App {
    public String getGreeting() {
        return "Welcome to Tic Tac Toe";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
